[tool.poetry]
name = "tech-coach-examples"
version = "0.1.0"
description = ""
authors = ["Arne Sørli <81353974+arneso-ssb@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
modin = {extras = ["ray"], version = "^0.20.1"}
jupyterlab = "^3.6.3"

[tool.poetry.dev-dependencies]
black = {extras = ["d", "jupyter"], version = "^23.3.0"}
ipykernel = "^6.22.0"
isort = "^5.12.0"
nbstripout = "^0.6.1"
pre-commit = "^3.3.1"
pre-commit-hooks = "^4.4.0"
pytest = "^7.3.1"

# Uncomment this section when working in the production zone
# [[tool.poetry.source]]
# name = "nexus"
# url = "http://pl-nexuspro-p.ssb.no:8081/repository/pypi-proxy/simple"
# default = true
# secondary = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
skip_gitignore = true
lines_after_imports = 2
