[data]
data-file1 = "data-feb-2024"

[paths]
inndata_dir = "test-stat/inndata"
klargjort_dir = "test-stat/klargjorte-data"

[storage]
bucket1 = "gs://ssb-tech-coach-data-produkt-prod"
bucket2 = "gs://ssb-prod-dapla-felles-data-delt/felles/eksempel"

[periods]
year = 2024

[misc]
center = "mcdavid"
